spring:
  datasource:
    url: 'jdbc:h2:mem:library;NON_KEYWORDS=USER'
    username: 'sa'
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  h2:
    console:
      enabled: true
      path: '/h2-console'